# Generated by Django 4.2.5 on 2023-09-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_name", models.CharField(max_length=200)),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("Axis_Bank", "Axis_Bank"),
                            ("ICICI_Bank", "ICICI_Bank"),
                            ("HDFC_Bank", "HDFC_Bank"),
                            ("SBI_Bank", "SBI_Bank"),
                            ("KOTAK_Bank", "KOTAK_Bank"),
                            ("AMERICAN_EXPRESS_Bank", "AMERICAN_EXPRESS_Bank"),
                            ("YES_Bank", "YES_Bank"),
                            ("Standard_Chartered_Bank", "Standard_Chartered_Bank"),
                            ("IndusInd_Bank", "IndusInd_Bank"),
                            ("RBL_Bank", "RBL_Bank"),
                            ("PNB_Bank", "PNB_Bank"),
                            ("IDFC_First_Bank", "IDFC_First_Bank"),
                            ("Indian_Bank", "Indian_Bank"),
                            ("BOI_Bank", "BOI_Bank"),
                            ("IDBI_Bank", "IDBI_Bank"),
                            ("CITI_Bank", "CITI_Bank"),
                            ("Canara_Bank", "Canara_Bank"),
                        ],
                        default="sbi",
                        max_length=200,
                    ),
                ),
                ("joining_fees", models.FloatField()),
                ("annual_fees", models.FloatField()),
                ("welcome_benefit", models.TextField(blank=True, max_length=500)),
            ],
        ),
    ]
