# Generated by Django 4.2.5 on 2023-09-24 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cardcomp", "0002_card_annual_fees_remark_card_joining_fees_remark"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_spec",
                    models.CharField(
                        choices=[
                            ("Grocery", "Grocery"),
                            ("food", "food"),
                            ("online_shopping", "online_shopping"),
                            ("utility_bill", "utility_bill"),
                            ("fuel", "fuel"),
                            ("movies", "movies"),
                            ("airline", "airline"),
                            ("other_features", "other_features"),
                        ],
                        default="other_features",
                        max_length=200,
                    ),
                ),
                ("offer_spec_abt", models.CharField(blank=True, max_length=200)),
                ("offer_spec_per", models.FloatField()),
                ("offer_spec_max_upto", models.FloatField()),
                ("offer_spec_freq", models.FloatField()),
                ("offer_spec_remark", models.TextField(blank=True, max_length=500)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cardcomp.card"
                    ),
                ),
            ],
        ),
    ]
